site_name: NNF
site_description: 'Near Node Flash'
docs_dir: docs/
repo_name: 'NearNodeFlash/NearNodeFlash.github.io'
repo_url: https://github.com/NearNodeFlash/NearNodeFlash.github.io
copyright: '&copy; Copyright 2023 Hewlett Packard Enterprise Development LP'
nav:
  - Home: index.md
  - 'User Guides':
      - guides/index.md
      - 'Initial Setup': 'guides/initial-setup/readme.md'
      - 'Compute Daemons': 'guides/compute-daemons/readme.md'
      - 'User Interactions': 'guides/user-interactions/readme.md'
      - 'Data Movement': 'guides/data-movement/readme.md'
      - 'Copy Offload': 'guides/data-movement/copy-offload.md'
      - 'Firmware Upgrade': 'guides/firmware-upgrade/readme.md'
      - 'High Availability Cluster': 'guides/ha-cluster/readme.md'
      - 'RBAC for Users': 'guides/rbac-for-users/readme.md'
      - 'Storage Profiles': 'guides/storage-profiles/readme.md'
      - 'User Containers': 'guides/user-containers/readme.md'
      - 'Lustre External MGT': 'guides/external-mgs/readme.md'
      - 'Global Lustre': 'guides/global-lustre/readme.md'
      - 'Disable or Drain a Node': 'guides/node-management/drain.md'
      - 'Auditing': 'guides/monitoring-cluster/auditing.md'
      - 'API Priority and Fairness': 'guides/monitoring-cluster/api-priority-and-fairness.md'
      - 'Debugging NVMe Namespaces': 'guides/node-management/nvme-namespaces.md'
      - 'Switch a Node From Worker to Master': 'guides/node-management/worker-to-master.md'
      - 'Directive Breakdown': 'guides/directive-breakdown/readme.md'
      - 'System Storage': 'guides/system-storage/readme.md'
  - 'RFCs':
      - rfcs/index.md
      - 'Rabbit Request For Comment Process': 'rfcs/0001/readme.md'
      - 'Rabbit Storage For Containerized Applications': 'rfcs/0002/readme.md'
  - 'Repo Guides':
      - 'Releasing NNF Software': 'repo-guides/release-nnf-sw/release-all.md'
      - 'CRD Version Bumper': 'repo-guides/crd-bumper/readme.md'
      - 'Editing APIs': 'repo-guides/crd-bumper/editing-apis.md'
theme:
  name: 'material'
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
  logo: img/logo.png
  favicon: img/logo.png
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - macros
  - section-index
extra:
  version:
    provider: mike
    default: latest
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
