name: Publish Release Documentation
on:
  release:
    types:
      - published

jobs:
  build:
    name: Publish Release Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install Dependencies
        run: |
          pip install --disable-pip-version-check -r mkdocs_requirements.txt

      - name: Configure Git
        run: |
          git config --local user.name "Doc Deploy Bot"
          git config --local user.email "bot@noreply.github.hpe.com"

      - name: mike deploy new version
        env:
          VERSION: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mike deploy --push --update-aliases "$VERSION" "latest"
          mike set-default --push latest
